# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TrackProfile2web
                                 A QGIS plugin
 Leaflet interactive web profiles.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-05-24
        copyright            : (C) 2019 by Matteo Ghetta
        email                : matteo.ghetta@faunalia.eu
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TrackProfile2web class from file TrackProfile2web.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .track_profile_2_web import TrackProfile2web
    return TrackProfile2web(iface)
